

name: Deploy prod
permissions:
  security-events: write


on:

  push:
    branches: [ "prod" ]

jobs:
  # This workflow contains a single job called "build"
  checkout:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: View Contents
        run: ls -l

      - uses: actions/upload-artifact@master
        with:
          name: checkout-artifact
          path: ./

  terraform_validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: checkout
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout-artifact
          path: ./

      - name: View Contents
        run: ls -l

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7 

      #- name: Find and Replace
      #  uses: jacobtomlinson/gha-find-replace@v3
      #  with:
      #    find: "dynamic_env"
      #    replace: "dev"
      #    regex: false
      #    include: "backend.tf"    

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        id: validate
        run: terraform validate


  terrascan_job:
    runs-on: ubuntu-latest
    needs: [checkout]
    name: terrascan-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
        #sarif_upload: true
        #non_recursive:
        #iac_dir:
        #policy_path:
        #skip_rules:
        #config_path:
        #webhook_url:
        #webhook_token:
  


  terraform_plan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [terraform_validate, terrascan_job]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout-artifact
          path: ./

      - name: View Contents
        run: ls -l

      #- name: Find and Replace
      #  uses: jacobtomlinson/gha-find-replace@v3
      #  with:
      #    find: "dynamic_env"
      #    replace: "dev"
      #    regex: false
      #    include: "backend.tf"    

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          ACCESSKEY_ID:  ${{ secrets.ACCESSKEY_ID }}
          ACCESSKEY_SECRET:  ${{ secrets.ACCESSKEY_SECRET }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=config/dev/terraform.tfvars -out=dev-plan.out
        env:
          ACCESSKEY_ID:  ${{ secrets.ACCESSKEY_ID }}
          ACCESSKEY_SECRET:  ${{ secrets.ACCESSKEY_SECRET }}

      - uses: actions/upload-artifact@master
        with:
          name: plan-output
          path: dev-plan.out


  #approval:
  #  runs-on: ubuntu-latest
  #  needs: [terraform_plan]
  #  steps:
  #    - name: send approval
  #      uses: varu3/slack-approval@main
  #      env:
  #        SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
  #        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  #        SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
  #        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
  #      timeout-minutes: 10

          
  terraform_apply:
     # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [terraform_plan, approval]
    environment: dev

     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout-artifact
          path: ./

      - uses: actions/download-artifact@master
        with:
          name: plan-output
           
      - name: View Contents
        run: ls -l

      #- name: Find and Replace
      #  uses: jacobtomlinson/gha-find-replace@v3
      #  with:
      #    find: "dynamic_env"
      #    replace: "dev"
      #    regex: false
      #    include: "backend.tf"    

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          ACCESSKEY_ID:  ${{ secrets.ACCESSKEY_ID }}
          ACCESSKEY_SECRET:  ${{ secrets.ACCESSKEY_SECRET }}

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve dev-plan.out
        env:
          ACCESSKEY_ID:  ${{ secrets.ACCESSKEY_ID }}
          ACCESSKEY_SECRET:  ${{ secrets.ACCESSKEY_SECRET }}
      
